### ISSUE TITLE
sass error with rubinus server

### ISSUE THREAD

**Issue by exocode** [rails/sass-rails#213]
Hi there, I dont know where to post? (sass/sass-rails/rubinus)?

I am switching to rubinus server by adding this to my gemfile:

```
ruby "2.1.0", :engine => "rbx", :engine_version => "2.2.6"
```

after trying to run any task (rails server, rake, bundle install) I get this error message:

`TypeError: Superclass mismatch: Object != Sass::Script::Tree::Node`

```
Error:[rake --tasks] rake aborted!
TypeError: Superclass mismatch: Object != Sass::Script::Tree::Node
kernel/delta/rubinius.rb:332:in `open_class_under'
kernel/delta/rubinius.rb:24:in `open_class'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/sass-3.2.12/lib/sass/script/literal.rb:7:in `__script__'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/sass-3.2.12/lib/sass/script/literal.rb:1:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:2:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `__script__'
kernel/bootstrap/array.rb:66:in `each'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass.rb:5:in `__script__'
kernel/bootstrap/array.rb:66:in `each'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-0.12.2/lib/compass.rb:4:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/compass-rails-1.0.3/lib/compass-rails.rb:1:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/bundler-1.6.2/lib/bundler/runtime.rb:76:in `require'
kernel/bootstrap/array.rb:66:in `each'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/bundler-1.6.2/lib/bundler/runtime.rb:72:in `require'
kernel/bootstrap/array.rb:66:in `each'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/bundler-1.6.2/lib/bundler/runtime.rb:61:in `require'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/bundler-1.6.2/lib/bundler.rb:132:in `require'
/Users/jan/RubymineProjects/gn2013/config/application.rb:13:in `__script__'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
/Users/jan/RubymineProjects/gn2013/rakefile:5:in `__script__'
kernel/common/kernel.rb:447:in `load'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/rake_module.rb:28:in `load_rakefile'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:683:in `raw_load_rakefile'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:94:in `load_rakefile'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:93:in `load_rakefile'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:77:in `run'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/lib/rake/application.rb:75:in `run'
/Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems/rake-10.3.1/bin/rake:33:in `__script__'
kernel/common/kernel.rb:447:in `load'
/Users/jan/.rbenv/versions/rbx-2.2.6/bin/rake:23:in `__script__'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:649:in `script'
kernel/loader.rb:831:in `main'
```

How can I resolve that?

here is the main part of my gemfile:

```
source 'https://rubygems.org'

ruby "2.1.0", :engine => "rbx", :engine_version => "2.2.6"

gem 'rails', '3.2.14'

group :production do
  gem 'puma'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

gem 'mongoid', "~> 3.1.0"
gem 'mongoid-tree', :require => 'mongoid/tree'
gem 'mongoid_slug'
gem 'localized_fields'
gem 'mongoid_geospatial', git: 'https://github.com/nofxx/mongoid_geospatial', branch: 'master'

gem 'rabl-rails'

gem 'kaminari'
gem 'cloudinary'
gem 'attachinary'

# social stuff
gem 'koala', "~> 1.8.0rc1"

group :assets do
  gem 'sass-rails', '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'compass-960-plugin'
  gem 'jasny_bootstrap_extension_rails'
  gem 'bootstrap-select-rails'
  gem 'bootstrap-datepicker-rails'
  gem 'bootstrap-timepicker-rails'
  gem 'bootstrap-wysihtml5-rails'
  gem 'rails-bootstrap-toggle-buttons'
  gem 'bootstrap-datetimepicker-rails'
  gem 'select2-rails'
  gem 'jquery-minicolors-rails'
  gem 'modernizr-rails'
  gem 'jquery-slimscroll-rails'
end

#must be outside of assets, because of compiling issues
gem 'bootstrap-sass', "~>2.3"
# we take our bootstrap-form gem because the errors are improved to our template
gem 'bootstrap-form', :git => "git://github.com/mediatainment/bootstrap-form.git", tag: "1-0-3"
gem 'compass-rails'
gem 'touchpunch-rails'
gem 'bootstrap-multiselect-rails'

group :test do
  gem 'cucumber', '1.2.5'
  gem 'cucumber-rails', '1.3.0', :require => false
  gem 'webmock'
  gem 'email_spec'
  gem 'database_cleaner'
  gem 'shoulda'
  gem 'capybara-select2'
  gem 'faker'
end

group :development, :test do
  gem 'zeus', '0.13.4.pre2'
  gem 'rspec-rails'
  gem 'json_spec', '~> 1.1.1'
  gem 'fabrication'
  gem 'mongoid-rspec'
  gem 'capybara'
  gem 'ruby_gntp'
  gem 'webrat'
  gem 'vcr'
end

```

**Comment by exocode** [comment]
thank you... three years after, I had the same issue again :-) and it helped!
