### ISSUE TITLE
Illegal nesting error

### ISSUE THREAD

**Issue by dankohn** [rails/sass-rails#307]
Hi, I have several files (that are mainly plain CSS) and have names like `combo.css.scss`. With sass-rails 5.0.1, I am now getting the error:
```
Sass::SyntaxError - Illegal nesting: Only properties may be nested beneath properties.
  (in /Users/dan/Dropbox/Documents/dev/chewy/app/assets/stylesheets/main/combo.scss:9):
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:13:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:38:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:38:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:57:in `visit_root'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:24:in `visit'
  sass (3.4.10) lib/sass/tree/root_node.rb:35:in `css_tree'
  sass (3.4.10) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.10) lib/sass/engine.rb:268:in `render'
  sass-rails (5.0.1) lib/sass/rails/template.rb:47:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
...
```
Most of these files are just CSS, not SASS, and renaming them to `combo.css` avoids the error but without the correct CSS loading.

I'm also getting some strange behavior where pages load correctly, but then when I load an ActiveAdmin page, I get this error, and then the pages I loaded earlier start failing. It seems like the asset pipeline is getting corrupted.

I'd appreciate suggestions.

**Comment by rafaelfranca** [comment]
sass-rails 5.0.1 deprecate `.css.scss` files extensions. If it is a CSS file you should use `.css`.

When you say: `without the correct CSS loading` what do you mean?

**Comment by josh** [comment]
You definitely shouldn't get this just because its `.css.scss` or just `.scss`. Either way the SCSS processor is running on it and would end up.

Could you paste the contents of `combo.scss` around line 9? Maybe there is some bad nesting or something.

**Comment by dankohn** [comment]
Here are lines 8 and 9 of combo.scss:
```
html{color:#000;background:#FFF}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0}table{border-collapse:collapse;border-spacing:0}fieldset,img{border:0}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal}ol,ul{list-style:none}caption,th{text-align:left}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal}q:before,q:after{content:''}abbr,acronym{border:0;font-variant:normal}sup{vertical-align:text-top}sub{vertical-align:text-bottom}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;*font-size:100%}legend{color:#000}#yui3-css-stamp.cssreset{display:none}
/*
```
I've been getting intermittent errors with Rails 4.2 but not 4.1.9. I am seeing them again (note that arbre is used by ActiveAdmin:
```
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", "4afbd4ca-d36b-48cf-bfea-c9110ba5fa50"]]
  Rendered /Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/app/views/active_admin/page/index.html.arb (71.1ms)
Completed 500 Internal Server Error in 92ms

NoMethodError - undefined method `bubbles?' for #000000
  (in /Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/app/assets/stylesheets/active_admin/print.scss):
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:161:in `transparent_parent?'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:43:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:38:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:38:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:52:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `block in visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:57:in `visit_root'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:36:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
  sass (3.4.10) lib/sass/tree/visitors/base.rb:24:in `visit'
  sass (3.4.10) lib/sass/tree/root_node.rb:35:in `css_tree'
  sass (3.4.10) lib/sass/tree/root_node.rb:20:in `render'
  sass (3.4.10) lib/sass/engine.rb:268:in `render'
  sass-rails (5.0.1) lib/sass/rails/template.rb:47:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (2.12.3) lib/sprockets/context.rb:197:in `block in evaluate'
  sprockets (2.12.3) lib/sprockets/context.rb:194:in `evaluate'
  sprockets (2.12.3) lib/sprockets/processed_asset.rb:12:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:374:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:395:in `circular_call_protection'
  sprockets (2.12.3) lib/sprockets/base.rb:373:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/bundled_asset.rb:16:in `initialize'
  sprockets (2.12.3) lib/sprockets/base.rb:377:in `build_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:94:in `block in build_asset'
  sprockets (2.12.3) lib/sprockets/caching.rb:58:in `cache_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:93:in `build_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:287:in `find_asset'
  sprockets (2.12.3) lib/sprockets/index.rb:61:in `find_asset'
  sprockets (2.12.3) lib/sprockets/environment.rb:75:in `find_asset'
  sprockets (2.12.3) lib/sprockets/base.rb:295:in `[]'
  sprockets-rails (2.2.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.2.2) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.2.2) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.2) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
  arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/lib/active_admin/views/pages/base.rb:27:in `block (2 levels) in build_active_admin_head'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/lib/active_admin/views/pages/base.rb:26:in `block in build_active_admin_head'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/lib/active_admin/views/pages/base.rb:24:in `build_active_admin_head'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/lib/active_admin/views/pages/base.rb:9:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/app/views/active_admin/page/index.html.arb:2:in `block in ___sers_dan__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin__fac____ca___app_views_active_admin_page_index_html_arb__614842494565404581_70317880795360'
  arbre (1.0.3) lib/arbre/context.rb:45:in `initialize'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/app/views/active_admin/page/index.html.arb:1:in `___sers_dan__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin__fac____ca___app_views_active_admin_page_index_html_arb__614842494565404581_70317880795360'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:143:in `render'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/dan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  wicked_pdf (0.11.0) lib/wicked_pdf/pdf_helper.rb:23:in `render_with_wicked_pdf'
   () Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/activeadmin-9fac1106ca01/lib/active_admin/page_controller.rb:14:in `index'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  activesupport (4.2.0) lib/active_support/callbacks.rb:308:in `block (2 levels) in halting'
  activesupport (4.2.0) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
  app/controllers/application_controller.rb:73:in `use_zone'
  activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
  activesupport (4.2.0) lib/active_support/callbacks.rb:307:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  bullet (4.14.2) lib/bullet/rack.rb:12:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/rack/developer_mode.rb:56:in `traced_call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call'
  rack-livereload (0.3.15) lib/rack/livereload.rb:23:in `_call'
  rack-livereload (0.3.15) lib/rack/livereload.rb:14:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.9.9.275) lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.4) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
  /Users/dan/Documents/dev/chewy/bin/rails:4:in `<main>'
```

**Comment by dankohn** [comment]
I am still seeing this error and am still confused by it. The strangest thing is that I get this error only in development mode, but not in test. However, when I copy test.rb to development.rb, it doesn't fix the error.

I would greatly appreciate suggestions for other things to try.

**Comment by dankohn** [comment]
More data: I'm seeing the error with Rails 4.1.9 and sass-rails 5.0.1 but there's no error when I downgrade to sass-rails 4.0.5.

I'm happy to try additional debugging if you can suggest what to look for.

**Comment by cwest** [comment]
I'm seeing this error with Rails 4.2, sass-rails 5.0.1, using jasmine-rails for testing JavaScript. Curiously, I _don't_ see it in development locally, but I _do_ see it in travis. [Here is an example.](https://travis-ci.org/cwest/not/builds/49278624#L440)

**Comment by dankohn** [comment]
I'm no longer seeing this issue with Rails 4.2.1. I'm still not sure what the cause was.

**Comment by bhfmts** [comment]
I ran into the same error and none of the options above worked :/
I thought the "require: false" was going to work but it didn't. 
What it worked for me was installing the [linter-scss][1] plugin for Atom. After  I installed, I compiled again and it worked. I hope it works for you too guys. 
Regards, Bernardo.


  [1]: https://atom.io/packages/linter-scss-lint
