### ISSUE TITLE
uninitialized constant Sprockets::SassCacheStore when upgrading to latest

### ISSUE THREAD

**Issue by jonricaurte** [rails/sass-rails#324]
Hi,

I'm currently using:

  gem 'sprockets', '~> 3.0.0.rc.2'
  gem 'sprockets-es6', require: 'sprockets/es6'
  gem 'sprockets-rails', '~> 2.2.4'
  gem 'sass-rails', '5.0.1'

When I try to upgrade to gem 'sass-rails', '5.0.2' or gem 'sass-rails', '5.0.3' I get the following error:

uninitialized constant Sprockets::SassCacheStore

Thanks.

**Comment by rafaelfranca** [comment]
Could you post the entire stack trace?

**Comment by zfben** [comment]
I have the same problem.

```
NameError - uninitialized constant Sprockets::SassCacheStore:
  activesupport (4.2.1) lib/active_support/dependencies.rb:533:in `load_missing_constant'
  activesupport (4.2.1) lib/active_support/dependencies.rb:184:in `const_missing'
  compass-rails (2.0.1) lib/compass-rails/patches/sass_importer.rb:10:in `evaluate'
  tilt (1.4.1) lib/tilt/template.rb:103:in `render'
  sprockets (3.0.0) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:73:in `call_processor'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:55:in `block in call_processors'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:54:in `call_processors'
  sprockets (3.0.0) lib/sprockets/loader.rb:103:in `load_asset_by_uri'
  sprockets (3.0.0) lib/sprockets/loader.rb:40:in `block in load'
  sprockets (3.0.0) lib/sprockets/loader.rb:170:in `fetch_asset_from_dependency_cache'
  sprockets (3.0.0) lib/sprockets/loader.rb:33:in `load'
  sprockets (3.0.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.0.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.0.0) lib/sprockets/bundle.rb:23:in `block in call'
  sprockets (3.0.0) lib/sprockets/utils.rb:183:in `dfs'
  sprockets (3.0.0) lib/sprockets/bundle.rb:24:in `call'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:73:in `call_processor'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:55:in `block in call_processors'
  sprockets (3.0.0) lib/sprockets/processor_utils.rb:54:in `call_processors'
  sprockets (3.0.0) lib/sprockets/loader.rb:103:in `load_asset_by_uri'
  sprockets (3.0.0) lib/sprockets/loader.rb:40:in `block in load'
  sprockets (3.0.0) lib/sprockets/loader.rb:170:in `fetch_asset_from_dependency_cache'
  sprockets (3.0.0) lib/sprockets/loader.rb:33:in `load'
  sprockets (3.0.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
  sprockets (3.0.0) lib/sprockets/cached_environment.rb:47:in `load'
  sprockets (3.0.0) lib/sprockets/base.rb:63:in `find_asset'
  sprockets (3.0.0) lib/sprockets/environment.rb:30:in `find_asset'
  sprockets (3.0.0) lib/sprockets/base.rb:89:in `[]'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:190:in `check_errors_for'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
  app/views/layouts/new.slim:5:in `_app_views_layouts_new_slim___4009766742226797751_70154055689580'
  actionview (4.2.1) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.1) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.1) lib/action_view/template.rb:143:in `render'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/ben/.rbenv/versions/2.2.1/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  app/controllers/pages_controller.rb:27:in `home'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack-xml_parser (1.0.1) lib/action_dispatch/xml_params_parser.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  puma (2.11.2) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.2) lib/puma/server.rb:375:in `process_client'
  puma (2.11.2) lib/puma/server.rb:262:in `block in run'
  puma (2.11.2) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by rafaelfranca** [comment]
By the backtrace it seems to be a compass-rails issue. @jonricaurte are you using compass-rails?

**Comment by hongmingChm** [comment]
Hi, I manage to solve the issue by fix the gem compass-rails to version 2.0.2 or more
There's this fix
https://github.com/Compass/compass-rails/commit/f2a14505508f19464da22fad14ba21e272946561
Please correct me if I'm wrong xD

**Comment by rafaelfranca** [comment]
@hongmingChm it is correct. Thank you for pointing to the right commit

**Comment by jonricaurte** [comment]
Looks like compass-rails is having a lot of problems with the latest version of sprockets, but there hasn't been any activity on the repo in a few months. Is there anything comparable to compass-rails?

**Comment by jonricaurte** [comment]
I just downloaded the compass stylesheets and copied them into my stylesheets folder.

**Comment by blackbiron** [comment]
having same issue, no luck with @hongmingChm's solution... so this is my wayout :
`gem 'compass-rails', github: 'Compass/compass-rails', branch: '2-0-stable'`

**Comment by ajsharp** [comment]
+1 same problem here.

**Comment by Bodacious** [comment]
+1 :frowning:

**Comment by kikocastro** [comment]
+ 1
