### ISSUE TITLE
Sass::SyntaxError: $color: 100 is not a color for `alpha'

### ISSUE THREAD

**Issue by itay-grudev** [rails/sass-rails#333]
I am having the following problem when running `rake assets:precompile` in production. Bellow is a full dump of the output.

I have no SASS/SCSS files and none of my bundled the gems is using SASS.

Everything works if I drop `sass-rails` from my Gemfile.

I repeat, the issue is not caused by a mistake in any file since I don't have any sass/scss files!

```
rake assets:precompile -v --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
rake aborted!
Sass::SyntaxError: $color: 100 is not a color for `alpha'
(sass):8366
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/funcall.rb:303:in `reformat_argument_error'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/funcall.rb:146:in `rescue in _perform'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/funcall.rb:123:in `_perform'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/node.rb:50:in `perform'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `map'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:157:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:8:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/root_node.rb:36:in `css_tree'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/root_node.rb:20:in `render'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/engine.rb:278:in `render'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:48:in `call'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:28:in `call'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in `block in load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in `load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `yield'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:63:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:70:in `find_all_linked_assets'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:138:in `block in find'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:136:in `find'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:162:in `compile'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
ArgumentError: $color: 100 is not a color
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/functions.rb:533:in `assert_type'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/functions.rb:887:in `alpha'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/funcall.rb:140:in `_perform'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/script/tree/node.rb:50:in `perform'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `block (2 levels) in visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `map'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:430:in `block in visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:428:in `visit_rule'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `block in with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:115:in `with_frame'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/stack.rb:79:in `with_base'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:158:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `map'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/base.rb:36:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:157:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/visitors/perform.rb:8:in `visit'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/root_node.rb:36:in `css_tree'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/tree/root_node.rb:20:in `render'
/var/lib/gems/2.1.0/gems/sass-3.4.15/lib/sass/engine.rb:278:in `render'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:48:in `call'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/sass_compressor.rb:28:in `call'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:86:in `load_asset_by_uri'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:45:in `block in load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/loader.rb:38:in `load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `yield'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:63:in `find_asset'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/base.rb:70:in `find_all_linked_assets'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:138:in `block in find'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:223:in `block in stat_tree'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:207:in `block in stat_directory'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:204:in `stat_directory'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/path_utils.rb:222:in `stat_tree'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:136:in `find'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/sprockets/manifest.rb:162:in `compile'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/var/lib/gems/2.1.0/gems/sprockets-3.2.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.1.0/gems/sprockets-rails-2.3.2/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/var/lib/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

**Comment by rafaelfranca** [comment]
Do you have any file containing `$color: 100`?

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by itay-grudev** [comment]
I found it!

I have the following in my CSS files:
```css
filter: alpha(50);
```
Apparently CSS gets processed with the SCSS processor and this isn't a valid SCSS.

**Comment by itay-grudev** [comment]
This is still a bug.

**Comment by rafaelfranca** [comment]
Could you provide a sample application where I can reproduce this problem and debug?

**Comment by itay-grudev** [comment]
Is this ok?

**Comment by rafaelfranca** [comment]
Thanks, I'll take a look

**Comment by GosuSheep** [comment]
Any update? I'm also having this issue. Any workaround?

**Comment by thehappycoder** [comment]
I had this.

Had to change alpha(100) to alpha(opacity=100) to get it to work.

**Comment by NodeUrsa** [comment]
remote:        rake aborted!
remote:        Sass::SyntaxError: $alpha: (0 0.9) is not a number for `rgba'
remote:        (sass):4982
remote:        /tmp/build_4733a37058f63ee20ff642a500875a3a/app/assets/config/manifest.js:3
remote:        (sass):4982
remote:        /tmp/build_4733a37058f63ee20ff642a500875a3a/vendor/bundle/ruby/2.4.0/gems/sass-3.5.3/lib/sass/script/tree/funcall.rb:315:in `reformat_argument_error'
remote:        /tmp/build_4733a37058f63ee20ff642a500875a3a/vendor/bundle/ruby/2.4.0/gems/sass-3.5.3/lib/sass/script/tree/funcall.rb:162:in `rescue in _perform'
remote:        /tmp/build_4733a37058f63ee20ff642a500875a3a/vendor/bundle/ruby/2.4.0/gems/sass-3.5.3/lib/sass/script/tree/funcall.rb:132:in `_perform'
remote:        /tmp/build_4733a37058f63ee20ff642a500875a3a/vendor/bundle/ruby/2.4.0/gems/sass-3.5.3/lib/sass/script/tree/node.rb:50:in `perform'
....

I'm getting this error when deploy to Heroku. how can I solve this problem?

**Comment by itay-grudev** [comment]
@guilleiguaran Why? Has the compiler been fixed?

**Comment by guilleiguaran** [comment]
Sorry for closing without explanation (closed all issues in bulk since this repo won't contain code anymore)

This issue seems to be present in `sass` library itself, not in `sass-rails`, `sass ` library was deprecated one year ago in favor of `sassc`/`dart-sass` and has as End Of Life date March 26th 2019 (that is tomorrow), so your best option is try if this works with sassc and if still failing open an issue in sassc-ruby repo: https://github.com/sass/sassc-ruby
