### ISSUE TITLE
uninitialized constant Sprockets::Engines (NameError)

### ISSUE THREAD

**Issue by masterkain** [rails/sass-rails#48]
Hello, using the latest rails master branch I get an exception when starting the app, I switched from a working 1aa7daeb0a32648aeec4a3705b24c2b7543f615d setup:

```
remote: git://github.com/rails/sass-rails.git
-revision: 1aa7daeb0a32648aeec4a3705b24c2b7543f615d
+revision: 9d60bc84906936bce6d67228f1cc2b72e2f33559
```

Generated at: https://github.com/rails/sass-rails/blob/master/lib/sass/rails/railtie.rb#L37

Stacktrace:

```
/Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/sass-rails-9d60bc849069/lib/sass/rails/railtie.rb:37:in `block in <class:Railtie>': uninitialized constant Sprockets::Engines (NameError)
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/activesupport/lib/active_support/lazy_load_hooks.rb:34:in `call'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/activesupport/lib/active_support/lazy_load_hooks.rb:34:in `execute_hook'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/activesupport/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `each'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/activesupport/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/application/bootstrap.rb:68:in `block in <module:Bootstrap>'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/initializable.rb:25:in `instance_exec'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/initializable.rb:25:in `run'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/initializable.rb:50:in `block in run_initializers'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/initializable.rb:49:in `each'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/initializable.rb:49:in `run_initializers'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/application.rb:97:in `initialize!'
from /Users/kain/.rvm/gems/ruby-1.9.3-preview1/bundler/gems/rails-410b0ec1b712/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
```

**Comment by BTC1M** [comment]
I have the same issue, and adding gem 'sprockets' in my gemfile doesn't fix it.
